# Generated by Django 5.0.4 on 2024-06-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_to_text', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecord',
            name='text_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
